- name: Copy check script
  ansible.builtin.copy:
    src: "{{ file_dir }}/docker_check.py"
    dest: "{{ base_path }}/docker_check.py"
  tags:
    - check_py

- name: RUN check containers script
  ansible.builtin.command: python3 "{{ base_path }}/docker_check.py"
  register: check_script
  failed_when:
     - check_script.stdout | regex_search('False', multiline=True, ignorecase=True)
  tags:
    - check_py    

- debug:
    msg: "{{ check_script.stdout_lines }}"
  tags:
    - check_py      