---
# tasks file for monitoring

#Prapare directories

- name: Make grafana data directory writeable
  file:
    path: "{{ item }}"
    owner: 472
    group: 0
    recurse: yes
    state: directory    
  loop:
    - "{{ grafana_docker_data_dir }}"
    - "{{ grafana_docker_conf_dir }}"
    - "{{ grafana_docker_log_dir }}"
    - "{{ grafana_docker_dir }}"
    - "{{ grafana_docker_conf_dir }}/provisioning/datasources"    
  tags:
    - install
    - prepare_dirs      

- name: Prepare dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ loki_docker_conf_dir }}"
    - "{{ loki_docker_log_dir }}"
    - "{{ loki_docker_dir }}"
    - "{{ promtail_docker_conf_dir }}"
    - "{{ promtail_docker_dir }}"
    - "{{ node_exporter_dir }}"
    - "{{ node_exporter_file_dir }}"
    - "{{ alertmanager_docker_dir }}"
    - "{{ alertmanager_docker_conf_dir }}"
    - "{{ alertmanager_docker_data_dir }}"
    - "{{ prometheus_docker_data_dir }}"    
  tags:
    - install
    - prepare_dirs

# Prepare docker daemon dir

- name: Prepare docker daemon dir
  file:
    path: "{{ docker_daemon_service_dir }}"
    state: directory
  tags:
    - never  
    - install
    - docker-daemon

- name: Copy docker daemon options
  template:
    src: options.conf.j2
    dest: "{{ docker_daemon_service_dir }}/options.conf"
  tags:
    - never   
    - install
    - docker-daemon

- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  tags:
    - never   
    - install
    - docker-daemon

# Loki log plugin for docker

## install loki plugin for docker logs

- name: install loki plugin for docker logs
  shell: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions && docker plugin ls
  ignore_errors: true
  tags:
    - never
    - install    
    - install-loki-plugin

## Enable loki plugin for docker logs

- name: install loki plugin for docker logs
  shell: docker plugin enable loki
  ignore_errors: true
  tags:
    - never
    - install    
    - enable-loki-plugin     

## Upgrade loki plugin for docker logs

- name: Upgrade loki plugin for docker log
  shell: docker plugin disable loki --force && docker plugin upgrade loki grafana/loki-docker-driver:latest --grant-all-permissions && docker plugin enable loki
  ignore_errors: true
  tags:
    - never
    - upgrade-loki-plugin     

- name: Restart docker
  systemd:
    name: docker
    state: restarted
  ignore_errors: true    
  tags:
    - never
    - install    
    - install-loki-plugin
    - enable-loki-plugin         
    - uninstall-loki-plugin       

## Uninstall loki plugin for docker logs

- name: install loki plugin for docker logs
  shell: docker plugin enable loki
  ignore_errors: true
  tags:
    - never
    - install    
    - disable-loki-plugin
    - uninstall-loki-plugin      

- name: Uninstall loki plugin for docker logs
  shell: docker plugin disable loki --force && docker plugin rm loki
  ignore_errors: true   
  tags:
    - never 
    - uninstall-loki-plugin 

# COPY CONFIG FILES

## Copy alertmanager config file

- name: Copy alertmanager config template
  copy:
    src: "{{ file_dir }}/alertmanager.yml"
    dest: "{{ alertmanager_docker_conf_dir }}/alertmanager.yml"    
  tags:
    - install
    - upgrade

## Copy loki config file

- name: Copy loki config template
  template:
    src: loki-config.yml.j2
    dest: "{{ loki_docker_conf_dir }}/local-config.yaml"
  tags:
    - install
    - upgrade

## Copy prometheus config file

- name: Copy loki config template
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_docker_data_dir }}/prometheus.yml"
  tags:
    - install
    - upgrade

## Copy promtail config file

- name: Copy promtail config template
  template:
    src: promtail-config.yml.j2
    dest: "{{ promtail_docker_conf_dir }}/config.yml"
  tags:
    - install
    - upgrade

## Copy docker-compose file
- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/docker-compose.yml"
  tags:
    - install
    - upgrade    

## Copy grafana.ini file
- name: Copy grafafna.ini template
  template:
    src: grafana.ini
    dest: "{{ grafana_docker_conf_dir }}/grafana.ini"
  tags:
    - install
    - upgrade    

## Copy datasources

- name: Copy grafana datasources
  template:
    src: datasource.yml.j2
    dest: "{{ grafana_docker_conf_dir }}/provisioning/datasources/datasource.yml" 
  tags:
    - install
    - upgrade     

## Stop existing monitoring docker-compose file

- name: Stop monitoring
  shell: docker-compose -f "{{ base_path }}/docker-compose.yml" down
  tags:
    - remove
    - upgrade

## Start monitoring docker-compose file

- name: Revive monitoring
  shell: docker-compose -f "{{ base_path }}/docker-compose.yml" up -d
  tags:
    - start
    - install
    - upgrade
