---
# tasks file for monitoring

#Prapare directories

- name: Make grafana data directory writeable
  file:
    path: "{{ item }}"
    owner: 472
    group: 0
    recurse: yes
    state: directory    
  loop:
    - "{{ grafana_docker_data_dir }}"
    - "{{ grafana_docker_conf_dir }}"
    - "{{ grafana_docker_log_dir }}"
    - "{{ grafana_docker_dir }}"
    - "{{ grafana_docker_conf_dir }}/provisioning/datasources"    
  tags:
    - install
    - set_permission      

- name: Prepare dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ loki_docker_conf_dir }}"
    - "{{ loki_docker_log_dir }}"
    - "{{ loki_docker_dir }}"
    - "{{ promtail_docker_conf_dir }}"
    - "{{ promtail_docker_dir }}"
    - "{{ node_exporter_dir }}"
    - "{{ node_exporter_file_dir }}"
    - "{{ alertmanager_docker_dir }}"
    - "{{ alertmanager_docker_conf_dir }}"
    - "{{ alertmanager_docker_data_dir }}"      
  tags:
    - install
    - set_permission

# Loki log plugin for docker

## install loki plugin for docker logs

- name: install loki plugin for docker logs
  shell: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions && docker plugin ls
  tags:
    - never
    - install-loki-plugin 

## Upgrade loki plugin for docker logs

- name: Upgrade loki plugin for docker log
  shell: docker plugin disable loki --force && docker plugin upgrade loki grafana/loki-docker-driver:latest --grant-all-permissions && docker plugin enable loki
  tags:
    - never
    - upgrade-loki-plugin     

- name: Restart docker
  systemd:
    name: docker
    state: restarted
  tags:
    - never
    - uninstall-loki-plugin    

## Uninstall loki plugin for docker logs

- name: Uninstall loki plugin for docker logs
  shell: docker plugin disable loki --force && docker plugin rm loki   
  tags:
    - never   

# COPY CONFIG FILES

## Copy loki config file

- name: Copy alertmanager config template
  copy:
    src: "{{ file_dir }}/alertmanager.yml"
    dest: "{{ alertmanager_docker_conf_dir }}/alertmanager.yml"    
  tags:
    - install
    - all 

## Copy loki config file

- name: Copy loki config template
  template:
    src: loki-config.yml.j2
    dest: "{{ loki_docker_conf_dir }}/local-config.yaml"
  tags:
    - install
    - all 

## Copy promtail config file

- name: Copy promtail config template
  template:
    src: promtail-config.yml.j2
    dest: "{{ promtail_docker_conf_dir }}/config.yml"
  tags:
    - install
    - all

## Copy docker-compose file
- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_docker_dir }}/docker-compose.yml"

## Copy grafana.ini file
- name: Copy grafafna.ini template
  template:
    src: grafana.ini
    dest: "{{ grafana_docker_conf_dir }}/grafana.ini"

## Copy datasources

- name: Copy grafana datasources
  template:
    src: datasource.yml.j2
    dest: "{{ grafana_docker_conf_dir }}/provisioning/datasources/datasource.yml"  

## Stop existing grafana docker-compose file

- name: Stop monitoring
  shell: docker-compose -f "{{ grafana_docker_dir }}/docker-compose.yml" down -t 15
  tags:
    - remove
    - upgrade

- name: Revive monitoring
  shell: docker-compose -f "{{ grafana_docker_dir }}/docker-compose.yml" up -d
  tags:
    - install
    - upgrade
