
#Prapare directories

- name: Check that docker and docker-compose are present
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose
  tags:
    - never   
    - install
    - docker-daemon

- name: Make grafana data directory writeable
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 472
    group: 0
    recurse: yes
    state: directory
    mode: 0755
  register: grafana_dirs_prepare  
  loop:
    - "{{ grafana_docker_data_dir }}"
    - "{{ grafana_docker_conf_dir }}"
    - "{{ grafana_docker_log_dir }}"
    - "{{ grafana_docker_dashboards_dir }}"
  tags:
    - install
    - prepare_dirs      

- name: Prepare dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ loki_docker_conf_dir }}"
    - "{{ loki_docker_log_dir }}"
    - "{{ promtail_docker_conf_dir }}"
    - "{{ alertmanager_docker_conf_dir }}"
    - "{{ alertmanager_docker_data_dir }}"
    - "{{ prometheus_docker_data_dir }}"
    - "{{ prometheus_docker_rules_dir }}"    
  tags:
    - install
    - prepare_dirs

# COPY CONFIG FILES

## Copy alertmanager config file

- name: Copy alertmanager config template
  ansible.builtin.copy:
    src: "{{ file_dir }}/alertmanager.yml"
    dest: "{{ alertmanager_docker_conf_dir }}/alertmanager.yml"
    mode: 0644 
  tags:
    - install
    - upgrade

- name: Copy alert rules
  ansible.builtin.copy:
    src: "{{ file_dir }}/alert_rules/{{ item }}"
    dest: "{{ prometheus_docker_rules_dir }}/{{ item }}"
  loop:
    - nodes.yml
  tags:
    - install
    - upgrade    

## Copy loki config file

- name: Copy loki config template
  ansible.builtin.template:
    src: loki-config.yml.j2
    dest: "{{ loki_docker_conf_dir }}/local-config.yaml"
    mode: 0644    
  tags:
    - install
    - upgrade

## Copy prometheus config file

- name: Copy prometheus config template
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_docker_data_dir }}/prometheus.yml"
    mode: 0644     
  tags:
    - install
    - upgrade

## Copy promtail config file

- name: Copy promtail config template
  ansible.builtin.template:
    src: promtail-config.yml.j2
    dest: "{{ promtail_docker_conf_dir }}/config.yml"
    mode: 0644     
  tags:
    - install
    - upgrade

## Copy docker-compose file

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/docker-compose.yml"
    mode: 0644     
  tags:
    - install
    - upgrade    

## Copy grafana.ini file

- name: Copy grafafna.ini template
  ansible.builtin.template:
    src: grafana.ini
    dest: "{{ grafana_docker_conf_dir }}/grafana.ini"
    owner: 472
    group: 0
    mode: 0644 
  tags:
    - install
    - upgrade    

- name: Check that "{{ grafana_docker_data_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ grafana_docker_data_dir }}"
  register: dirs_prepared
  tags:
    - install
    - upgrade
    - start    

- name: Check that "{{ grafana_docker_conf_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ grafana_docker_conf_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists  
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ grafana_docker_log_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ grafana_docker_log_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists  
  tags:
    - install
    - upgrade
    - start 

- name: Check that "{{ grafana_docker_log_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ grafana_docker_log_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ loki_docker_conf_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ loki_docker_conf_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ loki_docker_log_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ loki_docker_log_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ promtail_docker_conf_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ promtail_docker_conf_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ alertmanager_docker_conf_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ alertmanager_docker_conf_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ alertmanager_docker_data_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ alertmanager_docker_data_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start       

- name: Check that "{{ prometheus_docker_data_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ prometheus_docker_data_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start

- name: Check that "{{ prometheus_docker_rules_dir }}" directory exists
  ansible.builtin.stat:
    path: "{{ prometheus_docker_rules_dir }}"
  register: dirs_prepared
  when: dirs_prepared.stat.exists    
  tags:
    - install
    - upgrade
    - start     