---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/library/ubuntu:20.04
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e 
  ansible-lint
skip_list:
  - 'role_name'