---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
  - name: check that docker accessavle with TCP
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 2375
    delegate_to: localhost      
    
  - name: check that NODE-EXPORTER is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 9100
    delegate_to: localhost

  - name: check that GRAFANA is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 3000
    delegate_to: localhost        

  - name: check that CADVISOR is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 9092
    delegate_to: localhost    

  - name: check that PROMTAIL is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 9081
    delegate_to: localhost
    
  - name: check that ALERTMANAGER is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 9093
    delegate_to: localhost
    
  - name: check that PROMETHEUS is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 9090
    delegate_to: localhost
    
  - name: check that LOKI is ready
    ansible.builtin.wait_for:
      host: 192.168.122.201
      port: 3100
    delegate_to: localhost
    