global:
  resolve_timeout: 5m
  smtp_smarthost: 'mailhog:2525'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

  routes:
  - receiver: 'email'
    match_re:
      severity: 'critical'
    continue: true

templates:
- '/etc/alertmanager/templates/email.html'

receivers:
- name: 'web.hook'
  webhook_configs:
   - url: 'http://127.0.0.1:5001/'

- name: 'email'
  email_configs:
  - to: 'somebody1@somebody.zero'
    from: 'somebody@somebodyzero'
    headers:
      Subject: "TEST |  {{ .GroupLabels.alertname }} | {{ if gt (len .Alerts.Firing) 0 }}Problem{{ end }} {{ if gt (len .Alerts.Resolved) 0 }}Solved{{ end }}"
    html: '{{ template "email.html" . }}'
    send_resolved: true
    smarthost: "mailhog:2525"
    require_tls: false

inhibit_rules:
#- source_match:
#    severity: 'critical'
#  target_match:
#    severity: 'warning'
#  equal: ['alertname', 'dev', 'instance']

- source_match:
    severity: 'critical'
    alertname: 'Out of disk space'
  target_match:
    severity: 'warning'
  equal: ['alertname','instance','device']

- source_match:
    severity: 'critical'
    alertname: 'Out of disk space'
  target_match:
    severity: 'warning'
  equal: ['alertname','instance','device']

- source_match:
    severity: 'warning'
    alertname: "Out of disk space"
  target_match:
    severity: 'info'
  equal: ['alertname','instance','device']

- source_match:
    severity: 'critical'
    alertname: "Out of swap"
  target_match:
    severity: 'warning'
  equal: ['alertname','instance','hostname']
